# Generated by Django 5.0.6 on 2024-06-17 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='webapp/blog/')),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('image', models.ImageField(upload_to='webapp/discount/')),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('som', 'Sum'), ('$', 'S')], default='som', max_length=20)),
                ('count', models.PositiveBigIntegerField()),
                ('category_data', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True)),
                ('count', models.PositiveBigIntegerField(default=1)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateField(auto_created=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('Comment', models.CharField(max_length=300)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='webapp.product')),
            ],
        ),
    ]
