# Generated by Django 5.0.6 on 2024-06-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='webapp/product/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='create_data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='create_data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
