# Generated by Django 5.0.6 on 2024-06-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_product_image_alter_blog_create_data_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
