# Generated by Django 5.0.6 on 2024-06-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='About',
        ),
    ]
