# Generated by Django 5.0.6 on 2024-06-18 09:06

import webapp.help
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=webapp.help.SaveMediaFile.customer_image_path),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to=webapp.help.SaveMediaFile.customer_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=webapp.help.SaveMediaFile.customer_image_path),
        ),
    ]
