# Generated by Django 5.0.6 on 2024-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_about_image_alter_client_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='locatsiya',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
