# Generated by Django 5.0.6 on 2024-06-18 11:07

import webapp.help
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_orders_user_orders_locatsiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(default=1, upload_to=webapp.help.SaveMediaFile.customer_image_path),
            preserve_default=False,
        ),
    ]
